diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=D:/Git/mingw64/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
core.editor="C:\\Program Files\\Sublime Text 3\\subl.exe" -w
pull.rebase=false
credential.helper=manager
user.email=jvasquezn04@gmail.com
user.name=Jorge Vasquez
user.mail=vasquez.volta@gmail.com
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
color.ui=auto
merge.conflictstyle=diff3
core.editor='C:/Program Files/Sublime Text 3/sublime_text.exe' -n -w
filesystem.Oracle Corporation|14.0.2|-257959698.timestampresolution=1001 microseconds
filesystem.Oracle Corporation|14.0.2|-257959698.minracythreshold=0 nanoseconds
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
